import Head from 'next/head'

export default function Home() {
  return (
    <div className="flex flex-col w-screen justify-center items-center bg-gray-50 h-screen">
      <Head>
        <title>Image Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full flex items-center justify-center">
        <div className="w-full max-w-lg bg-white p-8 splash-shadow rounded-lg">
          <header className="flex flex-col items-center justify-center mb-12">
            <h1 className="text-xl font-medium text-gray-2 mb-4">Upload your image</h1>
            <span className="text-xs text-gray-3 font-medium">File should be jpg, jpeg, png, svg</span>
          </header>
        </div>
      </main>
    </div>
  )
}
